version: "3"

services:
   cassandra0:
      image: cassandra:latest
      # Docker constainer environment variable. We are using the
      # CASSANDRA_CLUSTER_NAME to name the cluster. This needs to be the same
      # across clusters. We are also declaring that DC1N1 is a seed node.

      environment:
            CASSANDRA_CLUSTER_NAME: tcluster
            CASSANDRA_DC: TDC1
      ports:
        - 9042:9042
    # networks:
     #      cassclus:
      #          ipv4_address: 10.0.75.11

      # Exposing ports for inter cluste communication. Note this is already
      # done by the docker file. Just being explict about it.

      expose:
                  # Intra-node communication
                  - 7000
                  # TLS intra-node communication
                  - 7001
                  # JMX
                  - 7199
                  # CQL
                  - 9042
                  # Thrift service
                  - 9160

   cassandra1:
      image: cassandra:latest

      environment:
            CASSANDRA_CLUSTER_NAME: tcluster
            CASSANDRA_DC: TDC1
            CASSANDRA_SEEDS: cassandra0
      # In case this is the first time starting up cassandra we need to ensure
      # that all nodes do not start up at the same time. Cassandra has a
      # 2 minute rule i.e. 2 minutes between each node boot up. Booting up
      # nodes simultaneously is a mistake. This only needs to happen the firt
      # time we bootup. Configuration below assumes if the Cassandra data
      # directory is empty it means that we are starting up for the first
      # time.
     # command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 60; fi && /docker-entrypoint.sh cassandra -f'
      depends_on:
        - cassandra0
    #  networks:
     #       cassclus:
      #        ipv4_address: 10.0.75.12

   back:
      image: web-tree/org.web-tree.trust.back:latest
      depends_on:
              - cassandra1
   #   Need to find some solution how to run this script before entrypoint
   #   command: ["/wait-for-it.sh", "--timeout=0" ,"10.0.75.12:9042"]

      environment:
           SPRING_APPLICATION_JSON: '{"spring": {"data": {"cassandra": {"contact-points": "cassandra0"}}}}'
      ports:
           - 9000:9000
    #  networks:
     #     cassclus:
      #       ipv4_address: 10.0.75.13



#networks:
 # cassclus:
  #  driver: overlay
   # ipam:
    #  driver: default
     # config:
      #  - subnet: 10.0.75.0/24
